language: ruby
sudo: required
group: legacy

before_script:
  - sudo mkdir /mnt/ramdisk
  - sudo mount -t tmpfs -o size=1024m tmpfs /mnt/ramdisk
  - sudo stop mysql
  - sudo mv /var/lib/mysql /mnt/ramdisk
  - sudo ln -s /mnt/ramdisk/mysql /var/lib/mysql && sleep 10

script:
  - sudo start mysql

after_failure:
  - sudo cat /var/log/mysql/error.log
  - sudo cat /var/log/mysql.*
